### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Rook1ex** [hexiao-cs/S2ADet#1]
when I try to run train.py ,   "ModuleNotFoundError: No module named 'global_var' " was happened  and  then I try to pip this module,it doesn't work.What can i do to solve this problem?

**Comment by hexiao0275** [comment]
I didn't find this error during the code run, the specific experimental environment is: pytorch==1.10.1 cudatoolkit==11.3.1 torchvision==0.11.2.

**Comment by hexiao-cs** [comment]
ok

**Comment by hexiao0275** [comment]
Are you running it on windows? The problem should be due to the lack of linux kernel, I run it on linux (ubuntu).
