### ISSUE TITLE
似乎有勘误

### ISSUE THREAD

**Issue by pororooooo** [hexiao-cs/S2ADet#2]
您好，作者。我在阅读您的论文S2ADet上面发现您在“First, to address the issue of hyperspectral information redundancy and aggregate the spatial and spectral information, the HID module uses principal component analysis (PCA) to obtain SpAtial (SA) aggregated information by aggregating spectral dimension data, as shown in Fig 1. Furthermore, we employ a band selection algorithm to select representative bands that retain high-quality spatial information, generating SpEtral (SE) aggregated information as another input to the network”这一块似乎讲SA与SE说反了。如果是我搞错了，还请见谅。

**Comment by hexiao0275** [comment]
你是正确的。这篇文章处于under review状态，完整版本的论文还未提交到arxiv上，因此存在一些混淆的说法，谢谢。
