### ISSUE TITLE
NoduleNotFoundError: No module named 'global_var'

### ISSUE THREAD

**Issue by ljqljq111** [hexiao-cs/S2ADet#5]
Hi, I meet a problem when I run this project
python3 test.py
the error info is :NoduleNotFoundError: No module named 'global_var',
in File "/root/workspace/S2ADet/utils/datasets.py", line 28, in <module>
import global_var
where  the global_var has been defined

**Comment by hexiao0275** [comment]
Are you running it on windows? The problem should be due to the lack of linux kernel, I run it on linux (ubuntu).

**Comment by ljqljq111** [comment]
NO，I run it on linux(ubuntu 20.04). I didn't find where the global_var defined, could you please tell me?Or maybe it come from the package which I didn't download

**Comment by LegionHXF** [comment]
When I run it on Windows, it also prompts ModuleNotFoundError: No module named 'global_var'. What's the reason? Do all of your successes run on Liunx?

**Comment by hexiao0275** [comment]
I added the global_var.py file a few days ago, please add this file to the code. My friend had a lot of problems running it with windows, so it's best to use linux.
