### ISSUE TITLE
处理原始数据代码

### ISSUE THREAD

**Issue by eqwrqwrqr** [hexiao-cs/S2ADet#6]
我想要生成sa和se信息的代码

**Comment by hexiao0275** [comment]
1. I uploaded the code sa_se_image_generate.zip for data preprocessing, for the sake of experimental fairness, the bandselect method (ONR) used is a parameter-free method, link to the paper in reference [51]: https://github.com/tanmlh/Optimal-Neighboring-Reconstruction-for-Hyperspectral-Band-Selection;
2. There are many ways to do principal component analysis, I used one of the simplest methods available on github, you can look for other methods, the probability of results may be better .

**Comment by hexiao0275** [comment]
see [sa_se_image_generate.zip](https://github.com/hexiao-cs/S2ADet/blob/main/sa_se_image_generate.zip)
