### ISSUE TITLE
HOD-1 dataset problem

### ISSUE THREAD

**Issue by Bangyan-Hu** [hexiao-cs/S2ADet#7]
Hello, when I tried to reproduce the results of the article, I obtained relatively similar results on the HOD3K data set, but the effect on the HOD-1 data set was very poor, and it was almost impossible to predict any effective targets.
So I have two questions:
First of all, since you only released the original multispectral data of the HOD-1 data set and did not disclose the processed SA and SE data, can you please release the processed data set?
Second, do you still use the same parameters [hyp.finetune.yaml](https://github.com/hexiao-cs/S2ADet/blob/main/data/hyp.finetune.yaml) on the HOD-1 data set?

**Comment by hexiao0275** [comment]
Hi. 1. I have uploaded the link to the HOD-1 processed dataset, which can be seen in Readme.md. Also, the generated code can be found in sa_se_image_generate.zip.
2. Yes, HOD-1 is also using the same setup in order to ensure the fairness of the experiments
