### ISSUE TITLE
Pre-generation SA

### ISSUE THREAD

**Issue by EmmaVanPuyenbr** [hexiao-cs/S2ADet#8]
In your paper, you refer to a pre-generation SA image compared to a post-generation SA image. Does this pre-generation SA image is the original image with 16 wavebands and without the ONR selection? and how did you then load it in the model? or what is the difference between pre and post?

**Comment by hexiao0275** [comment]
We initially employed the ONR algorithm to select three spectral bands from a set of sixteen, subsequently utilizing these selected bands to generate SA images.

**Comment by EmmaVanPuyenbr** [comment]
okay, and then what is the difference between post and pre-generated SA images?

**Comment by EmmaVanPuyenbr** [comment]
can you also still elaborate on this question?

**Comment by hexiao0275** [comment]
The pre-generated image is in the raw hyperspectral band and lacks textural detail. The generated operation is a preprocessing technique due to inconsistent number of bands and missing expression of band information.
